# -*- coding: utf-8 -*-
"""Time series -  checking stationarity using visualization and mean variance(Global Local test).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wsI3YfOfN8ySg7czIOnzmFQ3POxhZKEv
"""

import pandas as pd
import matplotlib.pyplot as plt

df=pd.read_csv('/content/airline-passengers.csv', header=0, index_col=0)
df.plot()

df.hist()

X=df
len(X)

#Splitting
split=round(len(X)/4)
split

X1,X2,X3,X4=X[0:36],X[36:split],X[split:108],X[108:]

mean1=X1.mean()

mean2=X2.mean()

mean3=X3.mean()

mean4=X4.mean()

(mean1,mean2,mean3,mean4)

var1=X1.std()
var2=X2.std()

print('mean')

(var1,var2)

import numpy as np
import math

Normalization=np.log(X)
print(Normalization)

Normalization.plot()

Normalization

df.hist()
Normalization.hist()

"""While Comparing, both histograms before and after applying log to bring normalization in data respectively, It's observed that after applying log, the data approximately have constant mean according to Gaussian/Normal distribution.

"""